---
- name: Ensure floating_ip variable is set
  fail:
    msg: Please set the floating_ip var
  when: floating_ip == false

- name: Ensure eth network script exists
  become: true
  template:
    src: templates/floating-ip-network.script.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0:1
  notify:
    - restart network
